// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  every_type_test: dynamic(() => import("./EveryTypeTest")),
  geopoint: dynamic(() => import("./Geopoint")),
  rich_text: dynamic(() => import("./RichText")),
};
